export const english: Record<string, string> = {
  添加词表: 'Add wordlist',
  导入文件: 'Import file',
  添加: 'Add',
  已添加: 'Added',
  '下载中…': 'Downloading…',
  词表来源: 'Wordlist source',
  '{0} 种词形': '{0} word forms',
  '{0} 个词条': '{0} headwords',
  'ECDICT 考试标签词表，包含中高考基础词和常见词形；六级包含四级。不代表官方大纲完整词表。':
    'ECDICT exam-tagged lists include school vocabulary and common inflections; CET-6 includes CET-4. Not complete official syllabuses.',
  未找到内置词表: 'Built-in wordlist not found',
  '词表下载失败，请重试': 'Download failed. Try again.',
  '词表校验失败，请重试': 'Wordlist verification failed. Try again.',

  开启: 'On',
  已暂停: 'Paused',
  在此网站启用: 'Enable on this site',
  此页面不支持: 'Unavailable on this page',
  '此页面未连接，请刷新网页后重试': 'Page not connected. Refresh it and try again.',
  已停用的网站: 'Disabled sites',
  恢复启用: 'Enable again',
  阅读功能已暂停: 'Reading is paused',

  纯数字不需要查询: 'Numbers do not need a lookup',
  '已获取 {0} 个模型': '{0} models found',
  '未找到模型，可以手动填写名称。': 'No models found. Enter a model name manually.',
  '获取失败，可手动填写模型。': 'Could not fetch models. You can enter a name manually.',
  'AI 连接': 'AI connection',
  'AI 连接帮助': 'AI connection help',
  '支持 OpenAI 兼容接口。测试连接会生成一组例句，不保存记录或制卡。':
    'Supports OpenAI-compatible APIs. Testing generates sample sentences without saving a record or creating a card.',
  'API 地址': 'API URL',
  密钥仅保存在此浏览器: 'Stored only in this browser',
  模型: 'Model',
  '正在获取…': 'Fetching…',
  获取模型: 'Get models',
  '连接正常 · 例句生成通过（{0} 秒）': 'Connected · Examples generated ({0} s)',
  '测试失败，请检查连接。': 'Test failed. Check the connection.',
  '正在测试…': 'Testing…',
  测试连接: 'Test connection',
  生成提示词: 'Generation prompt',
  提示词: 'Prompt',
  恢复默认提示词: 'Restore default prompt',
  '无法读取设置，请重新打开扩展': 'Could not load settings. Reopen the extension.',
  读取失败: 'Could not load data',
  '点一下，理解语境，记住表达。': 'Tap a word. Understand the context. Remember it.',
  页面: 'Pages',
  记录: 'Records',
  词表: 'Wordlists',
  设置: 'Settings',
  记录大小: 'Record density',
  紧凑: 'Compact',
  标准: 'Standard',
  搜索记录: 'Search records',
  '搜索词语或原句…': 'Search words or source sentences…',
  '正在删除 Anki 笔记…': 'Deleting Anki note…',
  重试删除: 'Retry deletion',
  '读取中…': 'Loading…',
  没有匹配的记录: 'No matching records',
  暂无记录: 'No records yet',
  '在网页上点选词语，语境和例句就会留在这里。':
    'Click a word on a webpage to keep its context and examples here.',
  '查看 {0} 详情': 'Details for {0}',
  已认识: 'Known',
  需要处理: 'Needs attention',
  记录分页: 'Record pages',
  上一页: 'Previous',
  下一页: 'Next',
  忽略语言: 'Ignored languages',
  '添加语言…': 'Add a language…',
  '移除{0}': 'Remove {0}',
  '连接已断开，请刷新页面': 'Connection lost. Refresh the page.',
  '已保存到 Anki': 'Saved to Anki',
  '已保存 · 等待 Anki': 'Saved · Waiting for Anki',
  已保存: 'Saved',
  '已记下，正在生成例句…': 'Saved. Generating examples…',
  语境查询: 'Context lookup',
  关闭: 'Close',
  停用同步: 'Off',
  原文: 'Source',
  暂时无法保存状态: 'Could not save the state',
  恢复学习: 'Keep learning',
  认识了: 'Mark as known',
  记录与设置: 'Records and settings',
  例句: 'Examples',
  无法读取记录: 'Could not load the record',
  操作未完成: 'Could not complete the action',
  关闭详情: 'Close details',
  简短释义: 'Short meaning',
  挖空表达: 'Target expression',
  取消编辑: 'Cancel editing',
  保存: 'Save',
  '删除这条学习记录？': 'Delete this learning record?',
  '同时删除 Anki 笔记': 'Also delete the Anki note',
  '将删除关联笔记及复习历史。': 'The linked note and its review history will be deleted.',
  'Anki 笔记会保留。': 'The Anki note will be kept.',
  取消删除: 'Cancel',
  确认删除: 'Delete',
  原文与来源: 'Source context',
  '删除这条来源？学习材料与 Anki 笔记会保留。':
    'Remove this source? Learning material and the Anki note will be kept.',
  移除来源: 'Remove source',
  上一组来源: 'Previous sources',
  下一组来源: 'Next sources',
  '等待 Anki': 'Waiting for Anki',
  '正在生成例句…': 'Generating examples…',
  编辑: 'Edit',
  重试: 'Retry',
  删除: 'Delete',
  '选择{0}': 'Select {0}',
  '可用{0}': 'Available {0}',
  '暂无模型，可刷新或手动填写。': 'No models yet. Refresh or enter a name.',
  '请检查 API 地址与连接选项': 'Check the URLs and connection settings',
  阅读与外观: 'Reading and appearance',
  阅读与外观帮助: 'Reading and appearance help',
  '选中词组或已认识的词后按 Alt + Q 查询。自动外观下弹窗跟随网页，记录页跟随系统，复习卡跟随 Anki。 忽略语言不高亮、不响应普通点击；主动选中后仍可用 Alt + Q 查询。':
    'Select a phrase or known word and press Alt + Q to look it up. Automatic appearance follows the webpage for lookups, the system for records, and Anki for cards. Ignored languages are not highlighted or triggered by clicks; Alt + Q remains available.',
  查询方式: 'Lookup gesture',
  点击词语: 'Click a word',
  'Alt + 点击词语': 'Alt + click a word',
  外观: 'Appearance',
  自动: 'Automatic',
  浅色: 'Light',
  深色: 'Dark',
  界面语言: 'Interface language',
  'Anki 帮助': 'Anki help',
  '打开 Anki 并安装': 'Open Anki and install',
  '。例句会自动制卡；Anki 未打开时先保存在本地。':
    '. Cards are created automatically. When Anki is closed, material stays saved locally.',
  'AnkiConnect 地址': 'AnkiConnect URL',
  'Anki 牌组': 'Anki deck',
  'AnkiConnect 密钥（可选）': 'AnkiConnect key (optional)',
  'Anki 连接正常': 'Anki is connected',
  '无法连接 Anki': 'Could not connect to Anki',
  '测试 Anki 连接': 'Test Anki connection',
  同步: 'Sync',
  同步帮助: 'Sync help',
  '在各设备填写同一工作区，阅读记录与词汇状态会自动合并。启用后每五分钟同步，离线时继续保存本地。 密钥、连接设置和本机 Anki 任务不参与同步；收到的记录不会重复制卡。远程数据未加密，请使用自己的私有存储。 测试连接只检查读取权限；保存后可立即同步。':
    'Use the same workspace on each device to merge reading records and vocabulary states. Sync runs every five minutes when enabled; offline changes stay local. Keys, connection settings and local Anki jobs are not synced. Received records do not create duplicate cards. Remote data is not encrypted; use private storage. Connection testing checks read access only. Save settings before syncing.',
  存储方式: 'Storage',
  'S3 地址': 'S3 endpoint',
  'WebDAV 地址': 'WebDAV URL',
  存储桶: 'Bucket',
  区域: 'Region',
  用户名: 'Username',
  密码: 'Password',
  工作区: 'Workspace',
  连接正常: 'Connected',
  连接失败: 'Connection failed',
  测试同步连接: 'Test sync connection',
  请先保存设置: 'Save settings first',
  同步失败: 'Sync failed',
  '正在同步…': 'Syncing…',
  立即同步: 'Sync now',
  上次同步: 'Last synced',
  导入词表: 'Import wordlist',
  选择词表文件: 'Choose a wordlist file',
  '词表文件不能超过 10 MB': 'Wordlist files must be under 10 MB',
  暂无词表: 'No wordlists yet',
  '导入自己的词表，减少熟悉词语的提醒，或专注于想学的词语。':
    'Import a wordlist to hide familiar words or focus on words you want to learn.',
  个词语: 'words',
  '移除词表 {0}': 'Remove wordlist {0}',
  移除词表: 'Remove wordlist',
  提醒用途: 'Use for reminders',
  忽略表内词: 'Ignore listed words',
  只提醒表内词: 'Only highlight listed words',
  已启用: 'Enabled',
  已停用: 'Disabled',
  词表帮助: 'Wordlist help',
  '支持 UTF-8 的 TXT、CSV 和 TSV，每份最多十万个词语。多份“只提醒表内词”合并生效，“忽略表内词”从中排除；个人明确标记的学习中或认识状态优先。移除词表不删除学习记录。':
    'Import UTF-8 TXT, CSV or TSV files with up to 100,000 words each. Focus lists combine; ignored lists exclude words from that set. Your explicit learning and known states take priority. Removing a list keeps your learning records.',
  名称: 'Name',
  ' · 已去重 {0} 项': ' · {0} duplicates removed',
  取消: 'Cancel',
  '正在导入…': 'Importing…',
  导入: 'Import',
  '移除词表？': 'Remove this wordlist?',
  '个人状态与学习记录会保留。': 'Your vocabulary states and learning records will be kept.',
  移除: 'Remove',
  '请使用 UTF-8 编码的词表': 'Use a UTF-8 encoded wordlist',
  '词表格式有误，请检查引号与分隔符': 'Invalid file format. Check quotes and delimiters.',
  '词表中有过长的词语，请检查文件格式': 'Some entries are too long. Check the file format.',
  每份词表最多导入十万个词语: 'A wordlist can contain up to 100,000 words',
  没有找到可导入的词语: 'No words found to import',
  '同步权限不足，请检查凭据与目录权限': 'Sync access denied. Check credentials and folder permissions.',
  '远程数据不符合格式，未应用该分片': 'Invalid remote data. The affected part was not applied.',
  '同步未完成，本地数据已保留；请检查连接或重试':
    'Sync did not complete. Local data is safe. Check the connection or retry.',
  请先配置并保存同步设置: 'Configure and save sync settings first',
  输入或返回内容不符合要求: 'Invalid input or response data',
  '扩展连接已断开，请刷新页面': 'Extension disconnected. Refresh the page.',
  任务正在进行: 'This task is already running',
  该条目已删除: 'This record has been deleted',
  未找到原始语境: 'Original context not found',
  编辑仅用于纠正释义与例句: 'Editing can only change meanings and examples',
  '返回数据不符合要求，请重试': 'Invalid response data. Please retry.',
  '条目已删除，请重新查询': 'This record was deleted. Look it up again.',
  '请等待 Anki 删除完成后重试': 'Wait for the Anki deletion to finish before retrying',
  未找到学习材料: 'Learning material not found',
  'Anki 内容已被修改，自动更新已暂停': 'The Anki content was edited. Automatic updates are paused.',
  '关联笔记已移除，未自动重新创建': 'The linked note was removed. It was not recreated.',
  '等待 Anki：请打开 Anki 并启用 AnkiConnect': 'Waiting for Anki. Open Anki and enable AnkiConnect.',
  '模型未正确定位原文，请重试': 'The model did not locate the original expression. Please retry.',
  模型解释的表达未包含选中内容: 'The model response does not include the selected text',
  '例句的目标表达不明确，请重试': 'The example target is ambiguous. Please retry.',
  '模型连接不可用，请稍后重试': 'The model is unavailable. Please try again later.',
  'API 密钥无效，请检查设置': 'Invalid API key. Check settings.',
  '模型未返回有效的结构化结果，请重试': 'The model returned invalid structured data. Please retry.',
  无法连接模型服务: 'Could not connect to the model service',
  '请更新 AnkiConnect 后重试': 'Update AnkiConnect and try again',
  'Anki 未完成操作，请检查 AnkiConnect 权限与牌组设置':
    'Anki could not complete the action. Check AnkiConnect permissions and deck settings.',
  '已有 TapGloss 笔记类型不兼容，请在 Anki 中检查，未修改现有模板':
    'The existing TapGloss note type is incompatible. Check it in Anki; existing templates were not changed.',
  '发现多份关联笔记，请在 Anki 中检查重复项': 'Multiple linked notes found. Check duplicates in Anki.',
  '无法确认笔记归属，未修改 Anki': 'Could not verify note ownership. Anki was not changed.',
};
